from Person import Person
from Job import Job
from Driver import Driver

#Inisialisi kelas Person dan pengisian data dummy
print("[Class: Person]")
person1 = Person()
person1.setNik("123456")
person1.setName("Raihan")
person1.setGender("Male")
person1.printData()
person1.sleep()

person2 = Person()
person2.setNik("654321")
person2.setName("Sarah")
person2.setGender("Female")
person2.printData()

person3 = Person()
person3.setNik("111111")
person3.setName("Amiya")
person3.setGender("Female")
person3.printData()
person3.sleep()

person4 = Person()
person4.setNik("212121")
person4.setName("Kazuha")
person4.setGender("Male")
person4.printData()

person5 = Person()
person5.setNik("104522")
person5.setName("Keqing")
person5.setGender("Female")
person5.printData()
person5.sleep()

#Inisialisi kelas Job dan pengisian data dummy
print("[Class: Job]")
job1 = Job()
job1.setNip("A1")
job1.setCompanyName("Bojek")
job1.setPosition("Driver")
job1.printData()

job2 = Job()
job2.setNip("B2")
job2.setCompanyName("Breb")
job2.setPosition("Driver")
job2.printData()

job3 = Job()
job3.setNip("C3")
job3.setCompanyName("Tuber")
job3.setPosition("Driver")
job3.printData()

job4 = Job()
job4.setNip("D4")
job4.setCompanyName("Si Lambat")
job4.setPosition("Driver")
job4.printData()

job5 = Job()
job5.setNip("E5")
job5.setCompanyName("Penguin Logistic")
job5.setPosition("Driver")
job5.printData()

#Inisialisi kelas Driver dan pengisian data dummy
print("[Class: Driver]")
driver1 = Driver()
driver1.setNik("123456")
driver1.setName("Raihan")
driver1.setGender("Male")
driver1.setNip("A1")
driver1.setCompanyName("Bojek")
driver1.setPosition("Driver")
driver1.setLisenceId("ID123")
driver1.setActiveUntil("15/12/2045")
driver1.printData()
driver1.sleep()

driver2 = Driver()
driver2.setNik("654321")
driver2.setName("Sarah")
driver2.setGender("Female")
driver2.setNip("B2")
driver2.setCompanyName("Breb")
driver2.setPosition("Driver")
driver2.setLisenceId("ID321")
driver2.setActiveUntil("12/12/2045")
driver2.printData()
driver2.sleep()

driver3 = Driver()
driver3.setNik("111111")
driver3.setName("Amiya")
driver3.setGender("Female")
driver3.setNip("C3")
driver3.setCompanyName("Tuber")
driver3.setPosition("Driver")
driver3.setLisenceId("ID111")
driver3.setActiveUntil("5/1/2035")
driver3.printData()
driver3.sleep()

driver4 = Driver()
driver4.setNik("212121")
driver4.setName("Kazuha")
driver4.setGender("Male")
driver4.setNip("D4")
driver4.setCompanyName("Si Lambat")
driver4.setPosition("Driver")
driver4.setLisenceId("ID212")
driver4.setActiveUntil("21/02/2040")
driver4.printData()
driver4.sleep()

driver5 = Driver()
driver5.setNik("104522")
driver5.setName("Keqing")
driver5.setGender("Female")
driver5.setNip("E5")
driver5.setCompanyName("Penguin Logistic")
driver5.setPosition("Driver")
driver5.setLisenceId("ID104")
driver5.setActiveUntil("15/12/2055")
driver5.printData()
driver5.sleep()